config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations]
  

  devise_scope :user do
   root to: "static#home"
   get    "login",  to: "devise/sessions#new",         as: :new_user_session
   post   "login",  to: "devise/sessions#create",      as: :user_session
   delete "logout", to: "devise/sessions#destroy",     as: :destroy_user_session

   get    "sign-up",  to: "devise/registrations#new",    as: :new_user_registration
   post   "sign-up",  to: "devise/registrations#create", as: :user_registration

end

  scope "/admin", module: :admin do
    resources :series do
        resources :videos
    end
  end

  get "admin", to: "admin/series#index"

  scope module: :users do
    get "/series", to: "series#index", as: :user_series_index
    get "/series/:id", to: "series#show", as: :user_series
    get "/watch/:id", to: "videos#show", as: :user_video
  end

end

app/controllers/admin/series_controller.rb
class Admin::SeriesController < ApplicationController
    
    def index
        @series = Series.all
    end

    def show
        @series = Series.find(params[:id])
        redirect_to series_videos_url(@series)
    end

    def new
        @series = Series.new
    end

    def create
        @series = Series.new(serie_params)
        if @series.save
            redirect_to series_url(@series), notice: "The serie  \"#{@series.title}\"  was built successfully."
        else
            render "new"
        end
    end

    def edit
        @series = Series.find(params[:id])
    end

    def update
        @series = Series.find(params[:id])
        if @series.update_attributes(serie_params)
            redirect_to series_url, notice: "The series \"#{@series.title}\" was updated successfully."
        else
            render "new"
        end
    end

    def destroy
        @series = Series.find(params[:id])
        if @series.destroy
            redirect_to series_index_url, notice: "The serie \"#{@series.title}\" was deleted successfully."
        else
            render "index"
        end
    end


    private

    def serie_params
        params.require(:series).permit(:title, :description, :level)
    end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
    
    def index
        @series = Series.all
    end

    def show
        @series = Series.find(params[:id])
        redirect_to series_videos_url(@series)
    end

    def new
        @series = Series.new
    end

    def create
        @series = Series.new(serie_params)
        if @series.save
            redirect_to series_url(@series), notice: "The serie  \"#{@series.title}\"  was built successfully."
        else
            render "new"
        end
    end

    def edit
        @series = Series.find(params[:id])
    end

    def update
        @series = Series.find(params[:id])
        if @series.update_attributes(serie_params)
            redirect_to series_url, notice: "The series \"#{@series.title}\" was updated successfully."
        else
            render "new"
        end
    end

    def destroy
        @series = Series.find(params[:id])
        if @series.destroy
            redirect_to series_index_url, notice: "The serie \"#{@series.title}\" was deleted successfully."
        else
            render "index"
        end
    end


    private

    def serie_params
        params.require(:series).permit(:title, :description, :level)
    end

end

app/controllers/users/series_controller.rb
class Users::SeriesController < ApplicationController

    def index
        @series = Series.all
    end

    def show
        @series = Series.find(params[:id])
        @videos = @series.videos.all
    end

end

app/views/admin/series/edit.html.erb
<%= render 'partials/errors', model: @series %>

<div class="row">
  <div class="col-md-6 column">

    <h2>Edit series</h2>
    <%= form_for @series, url: series_path , method: 'patch' do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :level %><br />
        <%= f.text_field :level, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-6 col-sm-offset-3">
            <%= f.submit "Edit series", class: "form-control btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %><br>

  </div>
</div>

app/views/admin/series/index.html.erb
<h1>All series</h1>
<%= link_to "Create series", new_series_url %><br><br>

<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>video count</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <% @series.each do |series| %>
        <tr>
            <td>
                 <%= series.id %>
            </td>
            <td>
                <%= series.title %>
            </td>
            <td>
                <%=  series.videos.count %>
            </td>       
            <td>
                <%= link_to "Edit", edit_series_url(series) %>
            </td>  
            <td>
                <%= link_to "View", series_videos_url(series) %>
            </td> 
            <td>
                <%= link_to series, :method => :delete, data: {confirm: "are your sure?"} do %>
                <%= octicon("trashcan", :height => 32,  :class => "right left", :"aria-label" => "hi") %>
                <% end %>
            </td>  
              
       </tr>
   <% end %>
</table>

app/views/admin/series/new.html.erb
<%= render 'partials/errors', model: @series %>

<div class="row">
  <div class="col-md-6 column">

    <h2>create serie</h2>
    <%= form_for @series, url: '/admin/series', method: 'post' do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :level %><br />
        <%= f.text_field :level, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-6 col-sm-offset-3">
            <%= f.submit "create serie", class: "form-control btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %><br>

  </div>
</div>

app/views/admin/series/show.html.erb
<h2>Welcome to  serie <%= @serie.title %></h2>