config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations]
  

  devise_scope :user do
   root to: "static#home"
   get    "login",  to: "devise/sessions#new",         as: :new_user_session
   post   "login",  to: "devise/sessions#create",      as: :user_session
   delete "logout", to: "devise/sessions#destroy",     as: :destroy_user_session

   get    "sign-up",  to: "devise/registrations#new",    as: :new_user_registration
   post   "sign-up",  to: "devise/registrations#create", as: :user_registration

end

  scope "/admin", module: :admin do
    resources :series do
        resources :videos
    end
  end

  get "admin", to: "admin/series#index"

  scope module: :users do
    get "/series", to: "series#index", as: :user_series_index
    get "/series/:id", to: "series#show", as: :user_series
    get "/watch/:id", to: "videos#show", as: :user_video
  end

end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :series 
    has_and_belongs_to_many :tags
    accepts_nested_attributes_for :tags, allow_destroy: true
    
    validates :title, presence: true  
    validates :url, presence: true
    validates :description, presence: true 
    validates_format_of :url, :with => URI::regexp(%w(http https))
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
    before_action :set_tags, only: [:create, :new, :edit]

    def set_tags
        @tags = Tag.all.map {|tag| [tag.name, tag.id] }
    end

    def index
        @series = Series.find(params[:series_id])
        @videos = @series.videos
    end

    def new
        @series = Series.find(params[:series_id])
        @video = @series.videos.new
    end

    def create
        @series = Series.find(params[:series_id])
        @video = @series.videos.new(video_params)
        selected_tags = params[:video][:tag_ids].reject!(&:blank?)
        if selected_tags.empty?
            flash[:error] = "Tag name can not be blank."
            render "new" and return
        end
        # add the existing tag or create the tag for that video.
        if @video.save

            selected_tags.each do |tag|
                tag_exists = Tag.exists?(tag)
                if tag_exists
                    @video.tags << Tag.find(tag)
                else
                    @tag = @video.tags.create(name: tag)
                end            
            end
            
            notice = "The video \"#{@video.title}\"  was built successfully."
            redirect_to series_videos_url(@series), notice: notice


        else                            
            render "new" 
        end
    end 

    def show
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
    end

    def edit
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
        @selected_tags = @video.tags.map {|tag| tag.name }
    end

    def update
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
        selected_tags = params[:video][:tag_ids].reject!(&:blank?)

        if @video.update_attributes(video_params)

            selected_tags.each do |tag|
                tag_exists = Tag.exists?(tag)
                video_tag_ids = @video.tags.map {|tag| tag.id }
                video_tag_included = video_tag_ids.include?(tag.to_i)

                if !tag_exists 
                     @tag = @video.tags.create(name: tag)
                elsif !video_tag_included
                  @video.tags << Tag.find(tag)      
                end            
            end
            redirect_to series_videos_url(@series), notice: "The video \"#{@video.title}\"  was updated successfully."
        else
            render "edit"
        end
    end

    def destroy
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
        if @video.destroy
            redirect_to series_videos_url, notice: "The video \"#{@video.title}\" was deleted successfully."
        else
            render "index"
        end
    end

    private

    def video_params
        params.require(:video).permit(:title, :url, :description)
    end

end

app/controllers/users/videos_controller.rb
class Users::VideosController < ApplicationController

    def show
     @video = Video.find(params[:id])
     Video.increment_counter(:view_count, @video.id)

      wh = WatchHistory.find_or_create_by(user_id: current_user.id, video_id: @video.id) do |wh|
        wh.user_id = current_user.id
        wh.video_id = @video.id
      end
      wh.touch(:last_watched_at)
    end

end     

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
        @series = Series.find(params[:series_id])
        @videos = @series.videos
    end

    def new
        @series = Series.find(params[:series_id])
        @video = @series.videos.new
    end

    def create
        @series = Series.find(params[:series_id])
        @video = @series.videos.create(video_params)
        if @video.save
            redirect_to series_videos_url(@series), notice: "The video \"#{@video.title}\"  was built successfully."
        else
            render "new"
        end
    end

    def show
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
    end

    def edit
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
    end

    def update
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
        if @video.update_attributes(video_params)
            redirect_to series_videos_url(@series), notice: "The video \"#{@video.title}\"  was updated successfully."
        else
            render "edit"
        end
    end

    def destroy
        @series = Series.find(params[:series_id])
        @video = @series.videos.find(params[:id])
        if @video.destroy
            redirect_to series_videos_url, notice: "The video \"#{@video.title}\" was deleted successfully."
        else
            render "index"
        end
    end

    private

    def video_params
        params.require(:video).permit(:title, :url, :description)
    end
end

app/views/admin/videos/edit.html.erb
<%= render 'partials/errors', model: @video %>

<div class="row">
  <div class="col-md-6 column">

    <h2>Edit Video</h2>
    <%= form_for @video, url: series_video_path(@series) , method: 'patch' do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :url %><br />
        <%= f.text_field :url, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group ">
        <%= f.select(:tag_ids, options_for_select(@tags), {include_blank: @selected_tags.to_sentence}, {multiple: true} ) %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-6 col-sm-offset-3">
            <%= f.submit "Edit Video", class: "form-control btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %><br>

  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#video_tag_ids').selectize({
      create: true,
      createOnBlur: true,
      maxItems: null,
      delimiter: ',',
      persist: true,
      hideSelected: false,
      preload: true,
      

      create: function(input) {
        return {
            value: input,
            text: input
        }
      }
    })
  });
</script>   

app/views/admin/videos/index.html.erb
<%= link_to "Create video", new_series_video_url(@series) %><br><br> 

<table class="table table-bordered text-center">
    <caption>List of videos for <%= @series.title %></caption>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    
    <% @videos.each do |video| %>
        <tbody>
            <tr>
                <td><%= video.title %></td>
                <td><%= video.description %></td>
                <td>
                    <%= link_to "Edit", edit_series_video_url(@series,video) %>
                </td>  
                <td>
                    <%= link_to "View", series_video_url(@series,video) %>
                </td> 
                <td>
                    <%= link_to [@series,video], :method => :delete, data: {confirm: "are your sure?"} do %>
                      <%= octicon("trashcan", :height => 32,  :class => "right left", :"aria-label" => "hi") %>
                    <% end %>
                </td>                 
            </tr>
        </tbody>
    <% end %>
</table>

app/views/admin/videos/new.html.erb
<%= render 'partials/errors', model: @video %>
<div class="row">
  <div class="col-md-6 column">

    <h2>Create Video</h2>
    <%= form_for @video, url: series_videos_path , method: 'post' do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :url %><br />
        <%= f.text_field :url, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.select(:tag_ids, options_for_select(@tags), {:prompt => 'Select Tag or add your own'}, { :multiple => true} ) %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br />
        <%= f.text_area :description, autocomplete: "current-level", class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-sm-6 col-sm-offset-3">
            <%= f.submit "Create Video", class: "form-control btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %><br>

  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#video_tag_ids').selectize({
      create: true,
      createOnBlur: true,
      maxItems: null,
      delimiter: ',',
      persist: true,
      hideSelected: false,

      create: function(input) {
        return {
            value: input,
            text: input
        }
      }
    })
  });
</script>

app/views/admin/videos/show.html.erb
    <h1>Title: <%= @video.title %><br><br>
        <tbody>
            <tr>
                <td>Tagged as:</td>
                <% tag_names = [] %>
                <% @video.tags.each do |tag|  %>
                    <td><% tag_names << tag.name %></td>
                <% end %>
                <%= tag_names.to_sentence %>
        </tbody>
           
    <iframe width="560" height="315" src="<%= @video.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>